# All the control signals generated by decode must be present here
instruction: str = None
pc: int = None

rs1: str = None
rs2: str = None
rd: str = None
func3: str = None
func7: str = None
op1: int = None
op2: int = None
opcode: str = None
# =========Immediate values========#
imm: int = None
immS: int = None
immU: int = None
immB: int = None
immJ: int = None
# ===========Control Signals==========#
OP2Select: int = None
ALUOperation: int = None
MemOp: int = None
ResultSelect: int = None
RFWrite: int = None
BranchTargetAddress: int = None

nop: int = None


def init():
    global instruction, pc, rs1, rs2, rd, func3, func7, op1, op2, opcode
    global imm, immS, immU, immB, immJ
    global OP2Select, ALUOperation, MemOp, ResultSelect, RFWrite, BranchTargetAddress
    global nop
    (
        instruction,
        pc,
        rs1,
        rs2,
        rd,
        func3,
        func7,
        op1,
        op2,
        opcode,
        imm,
        immS,
        immU,
        immB,
        immJ,
        OP2Select,
        ALUOperation,
        MemOp,
        ResultSelect,
        RFWrite,
        BranchTargetAddress,
        nop,
    ) = (
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
        None,
    )
